define([], function () {
    return [
      {
        "PY": "aba",
        "cityCode": 5132,
        "frameNumLen": 6,
        "id": 263,
        "motorNumLen": 6,
        "name": "阿坝",
        "prefix": "川U",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "akesu",
        "cityCode": 6529,
        "frameNumLen": 6,
        "id": 343,
        "motorNumLen": 0,
        "name": "阿克苏地区",
        "prefix": "新N",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "alashan",
        "cityCode": 1529,
        "frameNumLen": 6,
        "id": 40,
        "motorNumLen": 6,
        "name": "阿拉善盟",
        "prefix": "蒙M",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "aletai",
        "cityCode": 6543,
        "frameNumLen": 6,
        "id": 349,
        "motorNumLen": 0,
        "name": "阿勒泰地区",
        "prefix": "新H",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "alidiqu",
        "cityCode": 5425,
        "frameNumLen": 0,
        "id": 296,
        "motorNumLen": 6,
        "name": "阿里地区",
        "prefix": "藏F",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "ankang",
        "cityCode": 6109,
        "frameNumLen": -1,
        "id": 306,
        "motorNumLen": 6,
        "name": "安康",
        "prefix": "陕G",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "anqing",
        "cityCode": 3408,
        "frameNumLen": 6,
        "id": 110,
        "motorNumLen": 0,
        "name": "安庆",
        "prefix": "皖H",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "anshan",
        "cityCode": 2103,
        "frameNumLen": 4,
        "id": 43,
        "motorNumLen": 6,
        "name": "鞍山",
        "prefix": "辽C",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "anshun",
        "cityCode": 5204,
        "frameNumLen": 0,
        "id": 269,
        "motorNumLen": 6,
        "name": "安顺",
        "prefix": "贵G",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "anyang",
        "cityCode": 4105,
        "frameNumLen": 6,
        "id": 164,
        "motorNumLen": 6,
        "name": "安阳",
        "prefix": "豫E",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "baicheng",
        "cityCode": 2208,
        "frameNumLen": 4,
        "id": 62,
        "motorNumLen": 6,
        "name": "白城",
        "prefix": "吉G",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "baise",
        "cityCode": 4510,
        "frameNumLen": 0,
        "id": 236,
        "motorNumLen": 6,
        "name": "百色",
        "prefix": "桂L",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "baishan",
        "cityCode": 2206,
        "frameNumLen": 4,
        "id": 60,
        "motorNumLen": 6,
        "name": "白山",
        "prefix": "吉F",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "baiyin",
        "cityCode": 6204,
        "frameNumLen": -1,
        "id": 312,
        "motorNumLen": 0,
        "name": "白银",
        "prefix": "甘D",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "baoding",
        "cityCode": 1306,
        "frameNumLen": 4,
        "id": 10,
        "motorNumLen": 0,
        "name": "保定",
        "prefix": "冀F",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "baoji",
        "cityCode": 6103,
        "frameNumLen": -1,
        "id": 300,
        "motorNumLen": 6,
        "name": "宝鸡",
        "prefix": "陕C",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "baoshan",
        "cityCode": 5305,
        "frameNumLen": -1,
        "id": 278,
        "motorNumLen": 0,
        "name": "保山",
        "prefix": "云M",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "baotou",
        "cityCode": 1502,
        "frameNumLen": 6,
        "id": 30,
        "motorNumLen": 6,
        "name": "包头",
        "prefix": "蒙B",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "bayannaoer",
        "cityCode": 1508,
        "frameNumLen": 6,
        "id": 36,
        "motorNumLen": 6,
        "name": "巴彦淖尔盟",
        "prefix": "蒙L",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "bayinguoleng",
        "cityCode": 6528,
        "frameNumLen": 6,
        "id": 342,
        "motorNumLen": 0,
        "name": "巴音郭楞蒙古自治州",
        "prefix": "新M",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "bazhong",
        "cityCode": 5119,
        "frameNumLen": 6,
        "id": 261,
        "motorNumLen": 6,
        "name": "巴中",
        "prefix": "川Y",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "beihai",
        "cityCode": 4505,
        "frameNumLen": 0,
        "id": 231,
        "motorNumLen": 6,
        "name": "北海",
        "prefix": "桂E",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "beijing",
        "cityCode": 11,
        "frameNumLen": 0,
        "id": 1,
        "motorNumLen": -1,
        "name": "北京",
        "prefix": "京A",
        "province": "北京",
        "valid": true
      },
      {
        "PY": "bengbu",
        "cityCode": 3403,
        "frameNumLen": 6,
        "id": 105,
        "motorNumLen": 6,
        "name": "蚌埠",
        "prefix": "皖C",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "benxi",
        "cityCode": 2105,
        "frameNumLen": 4,
        "id": 45,
        "motorNumLen": 6,
        "name": "本溪",
        "prefix": "辽E",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "bijie",
        "cityCode": 5205,
        "frameNumLen": 0,
        "id": 270,
        "motorNumLen": 6,
        "name": "毕节",
        "prefix": "贵F",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "binzhou",
        "cityCode": 3716,
        "frameNumLen": -1,
        "id": 156,
        "motorNumLen": 0,
        "name": "滨州",
        "prefix": "鲁M",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "boertala",
        "cityCode": 6527,
        "frameNumLen": 6,
        "id": 341,
        "motorNumLen": 0,
        "name": "博尔塔拉蒙古自治州",
        "prefix": "新E",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "bozhou",
        "cityCode": 3416,
        "frameNumLen": 6,
        "id": 116,
        "motorNumLen": 0,
        "name": "亳州",
        "prefix": "皖S",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "cangzhou",
        "cityCode": 1309,
        "frameNumLen": 4,
        "id": 13,
        "motorNumLen": 0,
        "name": "沧州",
        "prefix": "冀J",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "cangzhouxingshu",
        "cityCode": 1312,
        "frameNumLen": 0,
        "id": 16,
        "motorNumLen": 0,
        "name": "沧州行署",
        "prefix": "冀S",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "changchun",
        "cityCode": 2201,
        "frameNumLen": 4,
        "id": 55,
        "motorNumLen": 0,
        "name": "长春",
        "prefix": "吉A",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "changde",
        "cityCode": 4307,
        "frameNumLen": 0,
        "id": 196,
        "motorNumLen": 6,
        "name": "常德",
        "prefix": "湘J",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "changdudiqu",
        "cityCode": 5421,
        "frameNumLen": 0,
        "id": 292,
        "motorNumLen": 6,
        "name": "昌都地区",
        "prefix": "藏B",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "changji",
        "cityCode": 6523,
        "frameNumLen": 6,
        "id": 340,
        "motorNumLen": 0,
        "name": "昌吉回族自治州",
        "prefix": "新B",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "changsha",
        "cityCode": 4301,
        "frameNumLen": 0,
        "id": 190,
        "motorNumLen": 6,
        "name": "长沙",
        "prefix": "湘A",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "changzhi",
        "cityCode": 1404,
        "frameNumLen": 6,
        "id": 20,
        "motorNumLen": 0,
        "name": "长治",
        "prefix": "晋D",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "changzhou",
        "cityCode": 3204,
        "frameNumLen": 0,
        "id": 82,
        "motorNumLen": 6,
        "name": "常州",
        "prefix": "苏D",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "chaohu",
        "cityCode": 340181,
        "frameNumLen": 0,
        "id": 350,
        "motorNumLen": 6,
        "name": "巢湖",
        "prefix": "皖Q",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "chaoyang",
        "cityCode": 2113,
        "frameNumLen": 0,
        "id": 53,
        "motorNumLen": 6,
        "name": "朝阳",
        "prefix": "辽N",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "chaozhou",
        "cityCode": 4451,
        "frameNumLen": 6,
        "id": 222,
        "motorNumLen": 6,
        "name": "潮州",
        "prefix": "粤U",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "chengde",
        "cityCode": 1308,
        "frameNumLen": 4,
        "id": 12,
        "motorNumLen": 0,
        "name": "承德",
        "prefix": "冀H",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "chengdu",
        "cityCode": 5101,
        "frameNumLen": 6,
        "id": 245,
        "motorNumLen": 0,
        "name": "成都",
        "prefix": "川A",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "chenzhou",
        "cityCode": 4310,
        "frameNumLen": 0,
        "id": 199,
        "motorNumLen": 6,
        "name": "郴州",
        "prefix": "湘L",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "chifeng",
        "cityCode": 1504,
        "frameNumLen": 6,
        "id": 32,
        "motorNumLen": 6,
        "name": "赤峰",
        "prefix": "蒙D",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "chizhou",
        "cityCode": 3417,
        "frameNumLen": 6,
        "id": 117,
        "motorNumLen": 6,
        "name": "池州",
        "prefix": "皖R",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "chongqing",
        "cityCode": 50,
        "frameNumLen": -1,
        "id": 4,
        "motorNumLen": 0,
        "name": "重庆",
        "prefix": "渝A",
        "province": "重庆",
        "valid": true
      },
      {
        "PY": "chongzuo",
        "cityCode": 4514,
        "frameNumLen": 0,
        "id": 240,
        "motorNumLen": 6,
        "name": "崇左",
        "prefix": "桂F",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "chuxiong",
        "cityCode": 5323,
        "frameNumLen": -1,
        "id": 283,
        "motorNumLen": 0,
        "name": "楚雄彝族自治州",
        "prefix": "云E",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "chuzhou",
        "cityCode": 3411,
        "frameNumLen": 6,
        "id": 112,
        "motorNumLen": 6,
        "name": "滁州",
        "prefix": "皖M",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "dali",
        "cityCode": 5329,
        "frameNumLen": -1,
        "id": 287,
        "motorNumLen": 0,
        "name": "大理白族自治州",
        "prefix": "云L",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "dalian",
        "cityCode": 2102,
        "frameNumLen": 4,
        "id": 42,
        "motorNumLen": 0,
        "name": "大连",
        "prefix": "辽B",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "dandong",
        "cityCode": 2106,
        "frameNumLen": 0,
        "id": 46,
        "motorNumLen": 6,
        "name": "丹东",
        "prefix": "辽F",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "daqing",
        "cityCode": 2306,
        "frameNumLen": -1,
        "id": 69,
        "motorNumLen": 0,
        "name": "大庆",
        "prefix": "黑E",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "datong",
        "cityCode": 1402,
        "frameNumLen": 6,
        "id": 18,
        "motorNumLen": 0,
        "name": "大同",
        "prefix": "晋B",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "daxinganling",
        "cityCode": 2327,
        "frameNumLen": -1,
        "id": 76,
        "motorNumLen": 0,
        "name": "大兴安岭地区",
        "prefix": "黑P",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "dazhou",
        "cityCode": 5117,
        "frameNumLen": 6,
        "id": 259,
        "motorNumLen": 6,
        "name": "达州",
        "prefix": "川S",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "dehong",
        "cityCode": 5331,
        "frameNumLen": -1,
        "id": 288,
        "motorNumLen": 0,
        "name": "德宏傣族景颇族自治州",
        "prefix": "云N",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "deyang",
        "cityCode": 5106,
        "frameNumLen": 6,
        "id": 249,
        "motorNumLen": 6,
        "name": "德阳",
        "prefix": "川F",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "dezhou",
        "cityCode": 3714,
        "frameNumLen": -1,
        "id": 154,
        "motorNumLen": 0,
        "name": "德州",
        "prefix": "鲁N",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "dingxi",
        "cityCode": 6211,
        "frameNumLen": -1,
        "id": 319,
        "motorNumLen": 0,
        "name": "定西",
        "prefix": "甘J",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "diqing",
        "cityCode": 5334,
        "frameNumLen": -1,
        "id": 290,
        "motorNumLen": 0,
        "name": "迪庆藏族自治州",
        "prefix": "云R",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "dongguan",
        "cityCode": 4419,
        "frameNumLen": 6,
        "id": 220,
        "motorNumLen": 6,
        "name": "东莞",
        "prefix": "粤S",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "dongying",
        "cityCode": 3705,
        "frameNumLen": -1,
        "id": 145,
        "motorNumLen": 0,
        "name": "东营",
        "prefix": "鲁E",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "eerduosi",
        "cityCode": 1506,
        "frameNumLen": 6,
        "id": 34,
        "motorNumLen": 6,
        "name": "鄂尔多斯",
        "prefix": "蒙K",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "enshi",
        "cityCode": 4228,
        "frameNumLen": 5,
        "id": 189,
        "motorNumLen": 0,
        "name": "恩施土家族苗族自治州",
        "prefix": "鄂Q",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "ezhou",
        "cityCode": 4207,
        "frameNumLen": 5,
        "id": 182,
        "motorNumLen": 0,
        "name": "鄂州",
        "prefix": "鄂G",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "fangchenggang",
        "cityCode": 4506,
        "frameNumLen": 0,
        "id": 232,
        "motorNumLen": 6,
        "name": "防城港",
        "prefix": "桂P",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "foshan",
        "cityCode": 4406,
        "frameNumLen": 6,
        "id": 209,
        "motorNumLen": 6,
        "name": "佛山",
        "prefix": "粤E",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "fu1zhou",
        "cityCode": 3501,
        "frameNumLen": 4,
        "id": 119,
        "motorNumLen": 0,
        "name": "福州",
        "prefix": "闽A",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "fushun",
        "cityCode": 2104,
        "frameNumLen": 4,
        "id": 44,
        "motorNumLen": 6,
        "name": "抚顺",
        "prefix": "辽D",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "futian",
        "cityCode": 3503,
        "frameNumLen": 4,
        "id": 121,
        "motorNumLen": 0,
        "name": "莆田",
        "prefix": "闽B",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "fuxin",
        "cityCode": 2109,
        "frameNumLen": 0,
        "id": 49,
        "motorNumLen": 6,
        "name": "阜新",
        "prefix": "辽J",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "fuyang",
        "cityCode": 3412,
        "frameNumLen": 6,
        "id": 113,
        "motorNumLen": 6,
        "name": "阜阳",
        "prefix": "皖K",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "fuzhou",
        "cityCode": 3610,
        "frameNumLen": 6,
        "id": 138,
        "motorNumLen": 6,
        "name": "抚州",
        "prefix": "赣F",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "gannan",
        "cityCode": 6230,
        "frameNumLen": -1,
        "id": 322,
        "motorNumLen": 0,
        "name": "甘南藏族自治州",
        "prefix": "甘P",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "ganzhou",
        "cityCode": 3607,
        "frameNumLen": 0,
        "id": 135,
        "motorNumLen": 6,
        "name": "赣州",
        "prefix": "赣B",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "ganzi",
        "cityCode": 5133,
        "frameNumLen": 6,
        "id": 264,
        "motorNumLen": 6,
        "name": "甘孜",
        "prefix": "川V",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "guangan",
        "cityCode": 5116,
        "frameNumLen": 6,
        "id": 258,
        "motorNumLen": 6,
        "name": "广安",
        "prefix": "川X",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "guangyuan",
        "cityCode": 5108,
        "frameNumLen": 6,
        "id": 251,
        "motorNumLen": 6,
        "name": "广元",
        "prefix": "川H",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "guangzhou",
        "cityCode": 4401,
        "frameNumLen": 6,
        "id": 204,
        "motorNumLen": 6,
        "name": "广州",
        "prefix": "粤A",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "guigang",
        "cityCode": 4508,
        "frameNumLen": 0,
        "id": 234,
        "motorNumLen": 6,
        "name": "贵港",
        "prefix": "桂R",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "guilin",
        "cityCode": 4503,
        "frameNumLen": 0,
        "id": 229,
        "motorNumLen": 6,
        "name": "桂林",
        "prefix": "桂C",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "guilindiqu",
        "cityCode": 4525,
        "frameNumLen": 0,
        "id": 241,
        "motorNumLen": 6,
        "name": "桂林地区",
        "prefix": "桂H",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "guiyang",
        "cityCode": 5201,
        "frameNumLen": 0,
        "id": 266,
        "motorNumLen": 6,
        "name": "贵阳",
        "prefix": "贵A",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "guoluocangzuzizhizhou",
        "cityCode": 6326,
        "frameNumLen": -1,
        "id": 328,
        "motorNumLen": 6,
        "name": "果洛藏族自治州",
        "prefix": "青F",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "guyuan",
        "cityCode": 6404,
        "frameNumLen": 0,
        "id": 334,
        "motorNumLen": 6,
        "name": "固原",
        "prefix": "宁D",
        "province": "宁夏",
        "valid": true
      },
      {
        "PY": "haerbin",
        "cityCode": 2301,
        "frameNumLen": -1,
        "id": 64,
        "motorNumLen": 0,
        "name": "哈尔滨",
        "prefix": "黑A",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "haibeicangzuzizhizhou",
        "cityCode": 6322,
        "frameNumLen": -1,
        "id": 325,
        "motorNumLen": 6,
        "name": "海北藏族自治州",
        "prefix": "青C",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "haidongdiqu",
        "cityCode": 6321,
        "frameNumLen": -1,
        "id": 324,
        "motorNumLen": 6,
        "name": "海东地区",
        "prefix": "青B",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "haikou",
        "cityCode": 4601,
        "frameNumLen": -1,
        "id": 242,
        "motorNumLen": 0,
        "name": "海口",
        "prefix": "琼A",
        "province": "海南",
        "valid": true
      },
      {
        "PY": "hainancangzuzizhizhou",
        "cityCode": 6325,
        "frameNumLen": -1,
        "id": 327,
        "motorNumLen": 6,
        "name": "海南藏族自治州",
        "prefix": "青E",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "haiximengguzucangzuzizhizhou",
        "cityCode": 6328,
        "frameNumLen": -1,
        "id": 330,
        "motorNumLen": 6,
        "name": "海西蒙古族藏族自治州",
        "prefix": "青H",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "hami",
        "cityCode": 6522,
        "frameNumLen": 6,
        "id": 339,
        "motorNumLen": 0,
        "name": "哈密地区",
        "prefix": "新L",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "handan",
        "cityCode": 1304,
        "frameNumLen": 4,
        "id": 8,
        "motorNumLen": 0,
        "name": "邯郸",
        "prefix": "冀D",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "hangzhou",
        "cityCode": 3301,
        "frameNumLen": 6,
        "id": 92,
        "motorNumLen": 0,
        "name": "杭州",
        "prefix": "浙A",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "hanzhong",
        "cityCode": 6107,
        "frameNumLen": -1,
        "id": 304,
        "motorNumLen": 6,
        "name": "汉中",
        "prefix": "陕F",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "hebi",
        "cityCode": 4106,
        "frameNumLen": 4,
        "id": 165,
        "motorNumLen": 6,
        "name": "鹤壁",
        "prefix": "豫F",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "hechi",
        "cityCode": 4512,
        "frameNumLen": 0,
        "id": 238,
        "motorNumLen": 6,
        "name": "河池",
        "prefix": "桂M",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "hefei",
        "cityCode": 3401,
        "frameNumLen": 6,
        "id": 103,
        "motorNumLen": 0,
        "name": "合肥",
        "prefix": "皖A",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "hegang",
        "cityCode": 2304,
        "frameNumLen": -1,
        "id": 67,
        "motorNumLen": 0,
        "name": "鹤岗",
        "prefix": "黑H",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "heihe",
        "cityCode": 2311,
        "frameNumLen": -1,
        "id": 74,
        "motorNumLen": 0,
        "name": "黑河",
        "prefix": "黑N",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "hengshui",
        "cityCode": 1311,
        "frameNumLen": 4,
        "id": 15,
        "motorNumLen": 0,
        "name": "衡水",
        "prefix": "冀T",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "hengyang",
        "cityCode": 4304,
        "frameNumLen": 0,
        "id": 193,
        "motorNumLen": 6,
        "name": "衡阳",
        "prefix": "湘D",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "hetian",
        "cityCode": 6532,
        "frameNumLen": 6,
        "id": 346,
        "motorNumLen": 0,
        "name": "和田地区",
        "prefix": "新R",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "heyuan",
        "cityCode": 4416,
        "frameNumLen": 6,
        "id": 217,
        "motorNumLen": 6,
        "name": "河源",
        "prefix": "粤P",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "heze",
        "cityCode": 3717,
        "frameNumLen": -1,
        "id": 157,
        "motorNumLen": 0,
        "name": "菏泽",
        "prefix": "鲁R",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "hezhou",
        "cityCode": 4511,
        "frameNumLen": 0,
        "id": 237,
        "motorNumLen": 6,
        "name": "贺州",
        "prefix": "桂J",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "honghe",
        "cityCode": 5325,
        "frameNumLen": -1,
        "id": 284,
        "motorNumLen": 0,
        "name": "红河哈尼族彝族自治州",
        "prefix": "云G",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "huaian",
        "cityCode": 3208,
        "frameNumLen": 0,
        "id": 86,
        "motorNumLen": 6,
        "name": "淮安",
        "prefix": "苏H",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "huaibei",
        "cityCode": 3406,
        "frameNumLen": 6,
        "id": 108,
        "motorNumLen": 6,
        "name": "淮北",
        "prefix": "皖F",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "huaihua",
        "cityCode": 4312,
        "frameNumLen": 0,
        "id": 201,
        "motorNumLen": 6,
        "name": "怀化",
        "prefix": "湘N",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "huainan",
        "cityCode": 3404,
        "frameNumLen": 6,
        "id": 106,
        "motorNumLen": 6,
        "name": "淮南",
        "prefix": "皖D",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "huanggang",
        "cityCode": 4211,
        "frameNumLen": 5,
        "id": 186,
        "motorNumLen": 0,
        "name": "黄冈",
        "prefix": "鄂J",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "huangnancangzuzizhizhou",
        "cityCode": 6323,
        "frameNumLen": -1,
        "id": 326,
        "motorNumLen": 6,
        "name": "黄南藏族自治州",
        "prefix": "青D",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "huangshan",
        "cityCode": 3410,
        "frameNumLen": 6,
        "id": 111,
        "motorNumLen": 6,
        "name": "黄山",
        "prefix": "皖J",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "huangshi",
        "cityCode": 4202,
        "frameNumLen": 5,
        "id": 178,
        "motorNumLen": 0,
        "name": "黄石",
        "prefix": "鄂B",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "huhehaote",
        "cityCode": 1501,
        "frameNumLen": 6,
        "id": 29,
        "motorNumLen": 6,
        "name": "呼和浩特",
        "prefix": "蒙A",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "huizhou",
        "cityCode": 4413,
        "frameNumLen": 6,
        "id": 214,
        "motorNumLen": 6,
        "name": "惠州",
        "prefix": "粤L",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "huludao",
        "cityCode": 2114,
        "frameNumLen": -1,
        "id": 54,
        "motorNumLen": 6,
        "name": "葫芦岛",
        "prefix": "辽P",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "hulunbeier",
        "cityCode": 1507,
        "frameNumLen": 6,
        "id": 35,
        "motorNumLen": 6,
        "name": "呼伦贝尔盟",
        "prefix": "蒙E",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "huzhou",
        "cityCode": 3305,
        "frameNumLen": 6,
        "id": 96,
        "motorNumLen": 0,
        "name": "湖州",
        "prefix": "浙E",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "jiamusi",
        "cityCode": 2308,
        "frameNumLen": -1,
        "id": 71,
        "motorNumLen": 0,
        "name": "佳木斯",
        "prefix": "黑D",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "jian",
        "cityCode": 3608,
        "frameNumLen": 6,
        "id": 136,
        "motorNumLen": 6,
        "name": "吉安",
        "prefix": "赣D",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "jiangmen",
        "cityCode": 4407,
        "frameNumLen": 6,
        "id": 210,
        "motorNumLen": 6,
        "name": "江门",
        "prefix": "粤J",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "jiaozuo",
        "cityCode": 4108,
        "frameNumLen": 6,
        "id": 167,
        "motorNumLen": 6,
        "name": "焦作",
        "prefix": "豫H",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "jiaxing",
        "cityCode": 3304,
        "frameNumLen": -1,
        "id": 95,
        "motorNumLen": -1,
        "name": "嘉兴",
        "prefix": "浙F",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "jiayuguan",
        "cityCode": 6202,
        "frameNumLen": -1,
        "id": 310,
        "motorNumLen": 0,
        "name": "嘉峪关",
        "prefix": "甘B",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "jieyang",
        "cityCode": 4452,
        "frameNumLen": 6,
        "id": 223,
        "motorNumLen": 6,
        "name": "揭阳",
        "prefix": "粤V",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "jilin",
        "cityCode": 2202,
        "frameNumLen": 4,
        "id": 56,
        "motorNumLen": 6,
        "name": "吉林",
        "prefix": "吉B",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "jinan",
        "cityCode": 3701,
        "frameNumLen": -1,
        "id": 141,
        "motorNumLen": 6,
        "name": "济南",
        "prefix": "鲁A",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "jinchang",
        "cityCode": 6203,
        "frameNumLen": -1,
        "id": 311,
        "motorNumLen": 0,
        "name": "金昌",
        "prefix": "甘C",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "jincheng",
        "cityCode": 1405,
        "frameNumLen": 6,
        "id": 21,
        "motorNumLen": 0,
        "name": "晋城",
        "prefix": "晋E",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "jingdezhen",
        "cityCode": 3602,
        "frameNumLen": 6,
        "id": 130,
        "motorNumLen": 6,
        "name": "景德镇",
        "prefix": "赣H",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "jingmen",
        "cityCode": 4208,
        "frameNumLen": 5,
        "id": 183,
        "motorNumLen": 0,
        "name": "荆门",
        "prefix": "鄂H",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "jingzhou",
        "cityCode": 4210,
        "frameNumLen": 5,
        "id": 185,
        "motorNumLen": 0,
        "name": "荆州",
        "prefix": "鄂D",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "jinhua",
        "cityCode": 3307,
        "frameNumLen": 6,
        "id": 98,
        "motorNumLen": 0,
        "name": "金华",
        "prefix": "浙G",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "jining",
        "cityCode": 3708,
        "frameNumLen": -1,
        "id": 148,
        "motorNumLen": 0,
        "name": "济宁",
        "prefix": "鲁H",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "jinzhong",
        "cityCode": 1407,
        "frameNumLen": 6,
        "id": 23,
        "motorNumLen": 0,
        "name": "晋中",
        "prefix": "晋K",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "jinzhou",
        "cityCode": 2107,
        "frameNumLen": 6,
        "id": 47,
        "motorNumLen": 6,
        "name": "锦州",
        "prefix": "辽G",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "jiujiang",
        "cityCode": 3604,
        "frameNumLen": 6,
        "id": 132,
        "motorNumLen": 6,
        "name": "九江",
        "prefix": "赣G",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "jiuquan",
        "cityCode": 6209,
        "frameNumLen": -1,
        "id": 317,
        "motorNumLen": 0,
        "name": "酒泉",
        "prefix": "甘F",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "jixi",
        "cityCode": 2303,
        "frameNumLen": -1,
        "id": 66,
        "motorNumLen": 0,
        "name": "鸡西",
        "prefix": "黑G",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "jiyuan",
        "cityCode": 419001,
        "frameNumLen": 0,
        "id": 351,
        "motorNumLen": 6,
        "name": "济源",
        "prefix": "豫U",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "kaifeng",
        "cityCode": 4102,
        "frameNumLen": -1,
        "id": 161,
        "motorNumLen": 6,
        "name": "开封",
        "prefix": "豫B",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "kashi",
        "cityCode": 6531,
        "frameNumLen": 6,
        "id": 345,
        "motorNumLen": 0,
        "name": "喀什地区",
        "prefix": "新Q",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "kelamayi",
        "cityCode": 6502,
        "frameNumLen": 6,
        "id": 337,
        "motorNumLen": 0,
        "name": "克拉玛依",
        "prefix": "新J",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "kezilesu",
        "cityCode": 6530,
        "frameNumLen": 6,
        "id": 344,
        "motorNumLen": 0,
        "name": "克孜勒苏柯尔克孜自治",
        "prefix": "新P",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "kuitun",
        "cityCode": 654003,
        "frameNumLen": 0,
        "id": 359,
        "motorNumLen": 6,
        "name": "奎屯",
        "prefix": "新D",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "kunming",
        "cityCode": 5301,
        "frameNumLen": -1,
        "id": 275,
        "motorNumLen": 4,
        "name": "昆明",
        "prefix": "云A",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "laibin",
        "cityCode": 4513,
        "frameNumLen": 0,
        "id": 239,
        "motorNumLen": 6,
        "name": "来宾",
        "prefix": "桂G",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "laiwu",
        "cityCode": 3712,
        "frameNumLen": -1,
        "id": 152,
        "motorNumLen": 6,
        "name": "莱芜",
        "prefix": "鲁S",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "langfang",
        "cityCode": 1310,
        "frameNumLen": 4,
        "id": 14,
        "motorNumLen": 0,
        "name": "廊坊",
        "prefix": "冀R",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "lanzhou",
        "cityCode": 6201,
        "frameNumLen": -1,
        "id": 309,
        "motorNumLen": 0,
        "name": "兰州",
        "prefix": "甘A",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "lasa",
        "cityCode": 5401,
        "frameNumLen": 0,
        "id": 291,
        "motorNumLen": 6,
        "name": "拉萨",
        "prefix": "藏A",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "leshan",
        "cityCode": 5111,
        "frameNumLen": 6,
        "id": 254,
        "motorNumLen": 6,
        "name": "乐山",
        "prefix": "川L",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "liangshanyizuzizhizhou",
        "cityCode": 5134,
        "frameNumLen": 6,
        "id": 265,
        "motorNumLen": 6,
        "name": "凉山彝族自治州",
        "prefix": "川W",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "lianyungang",
        "cityCode": 3207,
        "frameNumLen": 0,
        "id": 85,
        "motorNumLen": 6,
        "name": "连云港",
        "prefix": "苏G",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "liaocheng",
        "cityCode": 3715,
        "frameNumLen": -1,
        "id": 155,
        "motorNumLen": 0,
        "name": "聊城",
        "prefix": "鲁P",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "liaoyang",
        "cityCode": 2110,
        "frameNumLen": 0,
        "id": 50,
        "motorNumLen": 6,
        "name": "辽阳",
        "prefix": "辽K",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "liaoyuan",
        "cityCode": 2204,
        "frameNumLen": 4,
        "id": 58,
        "motorNumLen": 6,
        "name": "辽源",
        "prefix": "吉D",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "lijiang",
        "cityCode": 5307,
        "frameNumLen": -1,
        "id": 280,
        "motorNumLen": 0,
        "name": "丽江",
        "prefix": "云P",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "lincang",
        "cityCode": 5309,
        "frameNumLen": -1,
        "id": 282,
        "motorNumLen": 0,
        "name": "临沧",
        "prefix": "云S",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "linfen",
        "cityCode": 1410,
        "frameNumLen": 6,
        "id": 26,
        "motorNumLen": 0,
        "name": "临汾",
        "prefix": "晋L",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "linxia",
        "cityCode": 6229,
        "frameNumLen": -1,
        "id": 321,
        "motorNumLen": 0,
        "name": "临夏回族自治州",
        "prefix": "甘N",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "linyi",
        "cityCode": 3713,
        "frameNumLen": -1,
        "id": 153,
        "motorNumLen": 6,
        "name": "临沂",
        "prefix": "鲁Q",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "linzhidiqu",
        "cityCode": 5426,
        "frameNumLen": 0,
        "id": 297,
        "motorNumLen": 6,
        "name": "林芝地区",
        "prefix": "藏G",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "lishui",
        "cityCode": 3311,
        "frameNumLen": 6,
        "id": 102,
        "motorNumLen": 0,
        "name": "丽水",
        "prefix": "浙K",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "liuan",
        "cityCode": 3415,
        "frameNumLen": 6,
        "id": 115,
        "motorNumLen": 6,
        "name": "六安",
        "prefix": "皖N",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "liupanshui",
        "cityCode": 5202,
        "frameNumLen": 0,
        "id": 267,
        "motorNumLen": 6,
        "name": "六盘水",
        "prefix": "贵B",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "liuzhou",
        "cityCode": 4502,
        "frameNumLen": 0,
        "id": 228,
        "motorNumLen": 6,
        "name": "柳州",
        "prefix": "桂B",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "longnan",
        "cityCode": 6212,
        "frameNumLen": -1,
        "id": 320,
        "motorNumLen": 0,
        "name": "陇南",
        "prefix": "甘K",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "longyan",
        "cityCode": 3508,
        "frameNumLen": 4,
        "id": 126,
        "motorNumLen": 0,
        "name": "龙岩",
        "prefix": "闽F",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "loudi",
        "cityCode": 4313,
        "frameNumLen": 0,
        "id": 202,
        "motorNumLen": 6,
        "name": "娄底",
        "prefix": "湘K",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "luohe",
        "cityCode": 4111,
        "frameNumLen": 0,
        "id": 170,
        "motorNumLen": 6,
        "name": "漯河",
        "prefix": "豫L",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "luoyang",
        "cityCode": 4103,
        "frameNumLen": 0,
        "id": 162,
        "motorNumLen": -1,
        "name": "洛阳",
        "prefix": "豫C",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "luzhou",
        "cityCode": 5105,
        "frameNumLen": 6,
        "id": 248,
        "motorNumLen": 6,
        "name": "泸州",
        "prefix": "川E",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "lvliang",
        "cityCode": 1411,
        "frameNumLen": 6,
        "id": 27,
        "motorNumLen": 0,
        "name": "吕梁",
        "prefix": "晋J",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "maanshan",
        "cityCode": 3405,
        "frameNumLen": 6,
        "id": 107,
        "motorNumLen": 6,
        "name": "马鞍山",
        "prefix": "皖E",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "maoming",
        "cityCode": 4409,
        "frameNumLen": 6,
        "id": 212,
        "motorNumLen": 6,
        "name": "茂名",
        "prefix": "粤K",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "meishan",
        "cityCode": 5114,
        "frameNumLen": 6,
        "id": 256,
        "motorNumLen": 6,
        "name": "眉山",
        "prefix": "川Z",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "meizhou",
        "cityCode": 4414,
        "frameNumLen": 6,
        "id": 215,
        "motorNumLen": 6,
        "name": "梅州",
        "prefix": "粤M",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "mianyang",
        "cityCode": 5107,
        "frameNumLen": 6,
        "id": 250,
        "motorNumLen": 6,
        "name": "绵阳",
        "prefix": "川B",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "mudanjiang",
        "cityCode": 2310,
        "frameNumLen": -1,
        "id": 73,
        "motorNumLen": 0,
        "name": "牡丹江",
        "prefix": "黑C",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "nanchang",
        "cityCode": 3601,
        "frameNumLen": 6,
        "id": 129,
        "motorNumLen": 6,
        "name": "南昌",
        "prefix": "赣A",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "nanchangshi,shengzhixitong",
        "cityCode": 3612,
        "frameNumLen": 0,
        "id": 140,
        "motorNumLen": 6,
        "name": "南昌市,省直系统",
        "prefix": "赣M",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "nanchong",
        "cityCode": 5113,
        "frameNumLen": 6,
        "id": 255,
        "motorNumLen": 6,
        "name": "南充",
        "prefix": "川R",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "nanhaiqu",
        "cityCode": 4455,
        "frameNumLen": 6,
        "id": 226,
        "motorNumLen": 6,
        "name": "南海区",
        "prefix": "粤Y",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "nanjing",
        "cityCode": 3201,
        "frameNumLen": 0,
        "id": 79,
        "motorNumLen": 6,
        "name": "南京",
        "prefix": "苏A",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "nanning",
        "cityCode": 4501,
        "frameNumLen": 0,
        "id": 227,
        "motorNumLen": 6,
        "name": "南宁",
        "prefix": "桂A",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "nanping",
        "cityCode": 3507,
        "frameNumLen": 4,
        "id": 125,
        "motorNumLen": 0,
        "name": "南平",
        "prefix": "闽H",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "nantong",
        "cityCode": 3206,
        "frameNumLen": 0,
        "id": 84,
        "motorNumLen": 4,
        "name": "南通",
        "prefix": "苏F",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "nanyang",
        "cityCode": 4113,
        "frameNumLen": 4,
        "id": 172,
        "motorNumLen": 0,
        "name": "南阳",
        "prefix": "豫R",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "naqu",
        "cityCode": 5424,
        "frameNumLen": 0,
        "id": 295,
        "motorNumLen": 6,
        "name": "那曲地区",
        "prefix": "藏E",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "neijiang",
        "cityCode": 5110,
        "frameNumLen": 6,
        "id": 253,
        "motorNumLen": 6,
        "name": "内江",
        "prefix": "川K",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "ningbo",
        "cityCode": 3302,
        "frameNumLen": 6,
        "id": 93,
        "motorNumLen": 0,
        "name": "宁波",
        "prefix": "浙B",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "ningde",
        "cityCode": 3509,
        "frameNumLen": 4,
        "id": 127,
        "motorNumLen": 0,
        "name": "宁德",
        "prefix": "闽J",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "nongkenxitong",
        "cityCode": 2329,
        "frameNumLen": -1,
        "id": 78,
        "motorNumLen": 0,
        "name": "农垦系统",
        "prefix": "黑R",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "nujiang",
        "cityCode": 5333,
        "frameNumLen": -1,
        "id": 289,
        "motorNumLen": 0,
        "name": "怒江傈僳族自治州",
        "prefix": "云Q",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "panjin",
        "cityCode": 2111,
        "frameNumLen": 4,
        "id": 51,
        "motorNumLen": 6,
        "name": "盘锦",
        "prefix": "辽L",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "panzhihua",
        "cityCode": 5104,
        "frameNumLen": 6,
        "id": 247,
        "motorNumLen": 6,
        "name": "攀枝花",
        "prefix": "川D",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "pingdingshan",
        "cityCode": 4104,
        "frameNumLen": 0,
        "id": 163,
        "motorNumLen": 6,
        "name": "平顶山",
        "prefix": "豫D",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "pingliang",
        "cityCode": 6208,
        "frameNumLen": -1,
        "id": 316,
        "motorNumLen": 0,
        "name": "平凉",
        "prefix": "甘L",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "pingxiang",
        "cityCode": 3603,
        "frameNumLen": 6,
        "id": 131,
        "motorNumLen": 6,
        "name": "萍乡",
        "prefix": "赣J",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "puer",
        "cityCode": 5308,
        "frameNumLen": -1,
        "id": 281,
        "motorNumLen": 0,
        "name": "普洱",
        "prefix": "云J",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "puyang",
        "cityCode": 4109,
        "frameNumLen": 0,
        "id": 168,
        "motorNumLen": 0,
        "name": "濮阳",
        "prefix": "豫J",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "qiandongnan",
        "cityCode": 5226,
        "frameNumLen": 0,
        "id": 273,
        "motorNumLen": 6,
        "name": "黔东南苗族侗族自治州",
        "prefix": "贵H",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "qianjiang",
        "cityCode": 429005,
        "frameNumLen": 0,
        "id": 353,
        "motorNumLen": 6,
        "name": "潜江",
        "prefix": "鄂N",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "qiannan",
        "cityCode": 5227,
        "frameNumLen": 0,
        "id": 274,
        "motorNumLen": 6,
        "name": "黔南布依族苗族自治州",
        "prefix": "贵J",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "qianxinan",
        "cityCode": 5223,
        "frameNumLen": 0,
        "id": 272,
        "motorNumLen": 6,
        "name": "黔西南布依族苗族自治",
        "prefix": "贵E",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "qingdao",
        "cityCode": 3702,
        "frameNumLen": -1,
        "id": 142,
        "motorNumLen": 0,
        "name": "青岛",
        "prefix": "鲁B",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "qingdaoshizengbu",
        "cityCode": 3718,
        "frameNumLen": -1,
        "id": 158,
        "motorNumLen": 6,
        "name": "青岛市增补",
        "prefix": "鲁U",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "qingyang",
        "cityCode": 6210,
        "frameNumLen": -1,
        "id": 318,
        "motorNumLen": 0,
        "name": "庆阳",
        "prefix": "甘M",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "qingyuan",
        "cityCode": 4418,
        "frameNumLen": 6,
        "id": 219,
        "motorNumLen": 6,
        "name": "清远",
        "prefix": "粤R",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "qinhuangdao",
        "cityCode": 1303,
        "frameNumLen": 4,
        "id": 7,
        "motorNumLen": 0,
        "name": "秦皇岛",
        "prefix": "冀C",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "qinzhou",
        "cityCode": 4507,
        "frameNumLen": 0,
        "id": 233,
        "motorNumLen": 6,
        "name": "钦州",
        "prefix": "桂N",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "qionghai",
        "cityCode": 469002,
        "frameNumLen": -1,
        "id": 357,
        "motorNumLen": 0,
        "name": "琼海",
        "prefix": "琼C",
        "province": "海南",
        "valid": true
      },
      {
        "PY": "qiqihaer",
        "cityCode": 2302,
        "frameNumLen": -1,
        "id": 65,
        "motorNumLen": 0,
        "name": "齐齐哈尔",
        "prefix": "黑B",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "qitaihe",
        "cityCode": 2309,
        "frameNumLen": -1,
        "id": 72,
        "motorNumLen": 0,
        "name": "七台河",
        "prefix": "黑K",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "quanzhou",
        "cityCode": 3505,
        "frameNumLen": 4,
        "id": 123,
        "motorNumLen": 0,
        "name": "泉州",
        "prefix": "闽C",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "qujing",
        "cityCode": 5303,
        "frameNumLen": -1,
        "id": 276,
        "motorNumLen": 0,
        "name": "曲靖",
        "prefix": "云D",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "quzhou",
        "cityCode": 3308,
        "frameNumLen": 6,
        "id": 99,
        "motorNumLen": 0,
        "name": "衢州",
        "prefix": "浙H",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "rikazediqu",
        "cityCode": 5423,
        "frameNumLen": 0,
        "id": 294,
        "motorNumLen": 6,
        "name": "日喀则地区",
        "prefix": "藏D",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "rizhao",
        "cityCode": 3711,
        "frameNumLen": -1,
        "id": 151,
        "motorNumLen": 0,
        "name": "日照",
        "prefix": "鲁L",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "sanmenxia",
        "cityCode": 4112,
        "frameNumLen": -1,
        "id": 171,
        "motorNumLen": 6,
        "name": "三门峡",
        "prefix": "豫M",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "sanming",
        "cityCode": 3504,
        "frameNumLen": 4,
        "id": 122,
        "motorNumLen": 0,
        "name": "三明",
        "prefix": "闽G",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "sanya",
        "cityCode": 4602,
        "frameNumLen": -1,
        "id": 243,
        "motorNumLen": 0,
        "name": "三亚",
        "prefix": "琼B",
        "province": "海南",
        "valid": true
      },
      {
        "PY": "shanghai",
        "cityCode": 31,
        "frameNumLen": 0,
        "id": 3,
        "motorNumLen": -1,
        "name": "上海",
        "prefix": "沪A",
        "province": "上海",
        "valid": true
      },
      {
        "PY": "shangluo",
        "cityCode": 6110,
        "frameNumLen": -1,
        "id": 307,
        "motorNumLen": 6,
        "name": "商洛",
        "prefix": "陕H",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "shangqiu",
        "cityCode": 4114,
        "frameNumLen": -1,
        "id": 173,
        "motorNumLen": 6,
        "name": "商丘",
        "prefix": "豫N",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "shangrao",
        "cityCode": 3611,
        "frameNumLen": 6,
        "id": 139,
        "motorNumLen": 6,
        "name": "上饶",
        "prefix": "赣E",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "shannandiqu",
        "cityCode": 5422,
        "frameNumLen": 0,
        "id": 293,
        "motorNumLen": 6,
        "name": "山南地区",
        "prefix": "藏C",
        "province": "西藏",
        "valid": true
      },
      {
        "PY": "shantou",
        "cityCode": 4405,
        "frameNumLen": 6,
        "id": 208,
        "motorNumLen": 6,
        "name": "汕头",
        "prefix": "粤D",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "shanwei",
        "cityCode": 4415,
        "frameNumLen": 6,
        "id": 216,
        "motorNumLen": 6,
        "name": "汕尾",
        "prefix": "粤N",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "shaoguan",
        "cityCode": 4402,
        "frameNumLen": 6,
        "id": 205,
        "motorNumLen": 6,
        "name": "韶关",
        "prefix": "粤F",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "shaoxing",
        "cityCode": 3306,
        "frameNumLen": -1,
        "id": 97,
        "motorNumLen": 0,
        "name": "绍兴",
        "prefix": "浙D",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "shaoyang",
        "cityCode": 4305,
        "frameNumLen": 0,
        "id": 194,
        "motorNumLen": 6,
        "name": "邵阳",
        "prefix": "湘E",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "shengzhixitong",
        "cityCode": 3510,
        "frameNumLen": 0,
        "id": 128,
        "motorNumLen": 0,
        "name": "省直系统",
        "prefix": "闽K",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "shennongjia",
        "cityCode": 429021,
        "frameNumLen": 0,
        "id": 355,
        "motorNumLen": 6,
        "name": "神农架林区",
        "prefix": "鄂P",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "shenyang",
        "cityCode": 2101,
        "frameNumLen": 4,
        "id": 41,
        "motorNumLen": 0,
        "name": "沈阳",
        "prefix": "辽A",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "shenzhen",
        "cityCode": 4403,
        "frameNumLen": 6,
        "id": 206,
        "motorNumLen": 6,
        "name": "深圳",
        "prefix": "粤B",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "shihezi",
        "cityCode": 659001,
        "frameNumLen": 0,
        "id": 360,
        "motorNumLen": 6,
        "name": "石河子",
        "prefix": "新C",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "shijiazhuang",
        "cityCode": 1301,
        "frameNumLen": 4,
        "id": 5,
        "motorNumLen": 0,
        "name": "石家庄",
        "prefix": "冀A",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "shiyan",
        "cityCode": 4203,
        "frameNumLen": 5,
        "id": 179,
        "motorNumLen": 0,
        "name": "十堰",
        "prefix": "鄂C",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "shizuishan",
        "cityCode": 6402,
        "frameNumLen": 0,
        "id": 332,
        "motorNumLen": 6,
        "name": "石嘴山",
        "prefix": "宁B",
        "province": "宁夏",
        "valid": true
      },
      {
        "PY": "shuangyashan",
        "cityCode": 2305,
        "frameNumLen": -1,
        "id": 68,
        "motorNumLen": 0,
        "name": "双鸭山",
        "prefix": "黑J",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "shundequ",
        "cityCode": 4454,
        "frameNumLen": 6,
        "id": 225,
        "motorNumLen": 6,
        "name": "顺德区",
        "prefix": "粤X",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "shuozhou",
        "cityCode": 1406,
        "frameNumLen": 6,
        "id": 22,
        "motorNumLen": 0,
        "name": "朔州",
        "prefix": "晋F",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "siping",
        "cityCode": 2203,
        "frameNumLen": 4,
        "id": 57,
        "motorNumLen": 6,
        "name": "四平",
        "prefix": "吉C",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "songhuajiangdiqu",
        "cityCode": 2328,
        "frameNumLen": -1,
        "id": 77,
        "motorNumLen": 0,
        "name": "松花江地区",
        "prefix": "黑L",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "songyuan",
        "cityCode": 2207,
        "frameNumLen": 4,
        "id": 61,
        "motorNumLen": 6,
        "name": "松原",
        "prefix": "吉J",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "su1zhou",
        "cityCode": 3205,
        "frameNumLen": 7,
        "id": 83,
        "motorNumLen": 0,
        "name": "苏州",
        "prefix": "苏E",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "su4zhou",
        "cityCode": 3413,
        "frameNumLen": 6,
        "id": 114,
        "motorNumLen": 6,
        "name": "宿州",
        "prefix": "皖L",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "suihua",
        "cityCode": 2312,
        "frameNumLen": -1,
        "id": 75,
        "motorNumLen": 0,
        "name": "绥化",
        "prefix": "黑M",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "suining",
        "cityCode": 5109,
        "frameNumLen": 6,
        "id": 252,
        "motorNumLen": 6,
        "name": "遂宁",
        "prefix": "川J",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "suizhou",
        "cityCode": 4213,
        "frameNumLen": 5,
        "id": 188,
        "motorNumLen": 0,
        "name": "随州",
        "prefix": "鄂S",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "suqian",
        "cityCode": 3213,
        "frameNumLen": 0,
        "id": 91,
        "motorNumLen": 4,
        "name": "宿迁",
        "prefix": "苏N",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "tacheng",
        "cityCode": 6542,
        "frameNumLen": 6,
        "id": 348,
        "motorNumLen": 0,
        "name": "塔城地区",
        "prefix": "新G",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "tai1zhou",
        "cityCode": 3310,
        "frameNumLen": 6,
        "id": 101,
        "motorNumLen": 0,
        "name": "台州",
        "prefix": "浙J",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "taian",
        "cityCode": 3709,
        "frameNumLen": -1,
        "id": 149,
        "motorNumLen": 0,
        "name": "泰安",
        "prefix": "鲁J",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "taiyuan",
        "cityCode": 1401,
        "frameNumLen": 6,
        "id": 17,
        "motorNumLen": 0,
        "name": "太原",
        "prefix": "晋A",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "taizhou",
        "cityCode": 3212,
        "frameNumLen": 0,
        "id": 90,
        "motorNumLen": 6,
        "name": "泰州",
        "prefix": "苏M",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "tangshan",
        "cityCode": 1302,
        "frameNumLen": 4,
        "id": 6,
        "motorNumLen": 0,
        "name": "唐山",
        "prefix": "冀B",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "tianjin",
        "cityCode": 12,
        "frameNumLen": 0,
        "id": 2,
        "motorNumLen": 6,
        "name": "天津",
        "prefix": "津A",
        "province": "天津",
        "valid": true
      },
      {
        "PY": "tianmen",
        "cityCode": 429006,
        "frameNumLen": 0,
        "id": 354,
        "motorNumLen": 6,
        "name": "天门",
        "prefix": "鄂R",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "tianshui",
        "cityCode": 6205,
        "frameNumLen": -1,
        "id": 313,
        "motorNumLen": 0,
        "name": "天水",
        "prefix": "甘E",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "tieling",
        "cityCode": 2112,
        "frameNumLen": 0,
        "id": 52,
        "motorNumLen": 6,
        "name": "铁岭",
        "prefix": "辽M",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "tongchuan",
        "cityCode": 6102,
        "frameNumLen": -1,
        "id": 299,
        "motorNumLen": 6,
        "name": "铜川",
        "prefix": "陕B",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "tonghua",
        "cityCode": 2205,
        "frameNumLen": 4,
        "id": 59,
        "motorNumLen": 6,
        "name": "通化",
        "prefix": "吉E",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "tongliao",
        "cityCode": 1505,
        "frameNumLen": 6,
        "id": 33,
        "motorNumLen": 6,
        "name": "通辽",
        "prefix": "蒙G",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "tongling",
        "cityCode": 3407,
        "frameNumLen": 6,
        "id": 109,
        "motorNumLen": 6,
        "name": "铜陵",
        "prefix": "皖G",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "tongren",
        "cityCode": 5206,
        "frameNumLen": 0,
        "id": 271,
        "motorNumLen": 6,
        "name": "铜仁",
        "prefix": "贵D",
        "province": "贵州",
        "valid": true
      },
      {
        "PY": "tulufan",
        "cityCode": 6521,
        "frameNumLen": 6,
        "id": 338,
        "motorNumLen": 0,
        "name": "吐鲁番地区",
        "prefix": "新K",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "weifang",
        "cityCode": 3707,
        "frameNumLen": -1,
        "id": 147,
        "motorNumLen": 0,
        "name": "潍坊",
        "prefix": "鲁G",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "weifangshizengbu",
        "cityCode": 3719,
        "frameNumLen": -1,
        "id": 159,
        "motorNumLen": 0,
        "name": "潍坊市增补",
        "prefix": "鲁V",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "weihai",
        "cityCode": 3710,
        "frameNumLen": -1,
        "id": 150,
        "motorNumLen": 6,
        "name": "威海",
        "prefix": "鲁K",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "weinan",
        "cityCode": 6105,
        "frameNumLen": -1,
        "id": 302,
        "motorNumLen": 6,
        "name": "渭南",
        "prefix": "陕E",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "wenshan",
        "cityCode": 5326,
        "frameNumLen": -1,
        "id": 285,
        "motorNumLen": 0,
        "name": "文山壮族苗族自治州",
        "prefix": "云H",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "wenzhou",
        "cityCode": 3303,
        "frameNumLen": 6,
        "id": 94,
        "motorNumLen": 0,
        "name": "温州",
        "prefix": "浙C",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "wuhai",
        "cityCode": 1503,
        "frameNumLen": 6,
        "id": 31,
        "motorNumLen": 6,
        "name": "乌海",
        "prefix": "蒙C",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "wuhan",
        "cityCode": 4201,
        "frameNumLen": 6,
        "id": 177,
        "motorNumLen": 0,
        "name": "武汉",
        "prefix": "鄂A",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "wuhu",
        "cityCode": 3402,
        "frameNumLen": 6,
        "id": 104,
        "motorNumLen": 0,
        "name": "芜湖",
        "prefix": "皖B",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "wulanchabu",
        "cityCode": 1509,
        "frameNumLen": 6,
        "id": 37,
        "motorNumLen": 6,
        "name": "乌兰察布盟",
        "prefix": "蒙J",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "wulumuqi",
        "cityCode": 6501,
        "frameNumLen": 6,
        "id": 336,
        "motorNumLen": 0,
        "name": "乌鲁木齐",
        "prefix": "新A",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "wuwei",
        "cityCode": 6206,
        "frameNumLen": -1,
        "id": 314,
        "motorNumLen": 0,
        "name": "武威",
        "prefix": "甘H",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "wuxi",
        "cityCode": 3202,
        "frameNumLen": 0,
        "id": 80,
        "motorNumLen": 6,
        "name": "无锡",
        "prefix": "苏B",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "wuzhishan",
        "cityCode": 469001,
        "frameNumLen": -1,
        "id": 356,
        "motorNumLen": 0,
        "name": "五指山",
        "prefix": "琼D",
        "province": "海南",
        "valid": true
      },
      {
        "PY": "wuzhong",
        "cityCode": 6403,
        "frameNumLen": 0,
        "id": 333,
        "motorNumLen": 6,
        "name": "吴忠",
        "prefix": "宁C",
        "province": "宁夏",
        "valid": true
      },
      {
        "PY": "wuzhou",
        "cityCode": 4504,
        "frameNumLen": 0,
        "id": 230,
        "motorNumLen": 6,
        "name": "梧州",
        "prefix": "桂D",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "xiamen",
        "cityCode": 3502,
        "frameNumLen": 6,
        "id": 120,
        "motorNumLen": 0,
        "name": "厦门",
        "prefix": "闽D",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "xian",
        "cityCode": 6101,
        "frameNumLen": 0,
        "id": 298,
        "motorNumLen": -1,
        "name": "西安",
        "prefix": "陕A",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "xiangtan",
        "cityCode": 4303,
        "frameNumLen": 0,
        "id": 192,
        "motorNumLen": 6,
        "name": "湘潭",
        "prefix": "湘C",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "xiangxitujiazumiaozuzizhizhou",
        "cityCode": 4331,
        "frameNumLen": 0,
        "id": 203,
        "motorNumLen": 6,
        "name": "湘西土家族苗族自治州",
        "prefix": "湘U",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "xiangyang",
        "cityCode": 4206,
        "frameNumLen": 5,
        "id": 181,
        "motorNumLen": 0,
        "name": "襄阳",
        "prefix": "鄂F",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "xianning",
        "cityCode": 4212,
        "frameNumLen": 5,
        "id": 187,
        "motorNumLen": 0,
        "name": "咸宁",
        "prefix": "鄂L",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "xiantao",
        "cityCode": 429004,
        "frameNumLen": 0,
        "id": 352,
        "motorNumLen": 6,
        "name": "仙桃",
        "prefix": "鄂M",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "xianyang",
        "cityCode": 6104,
        "frameNumLen": -1,
        "id": 301,
        "motorNumLen": 6,
        "name": "咸阳",
        "prefix": "陕D",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "xiaogan",
        "cityCode": 4209,
        "frameNumLen": 5,
        "id": 184,
        "motorNumLen": 0,
        "name": "孝感",
        "prefix": "鄂K",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "xichang",
        "cityCode": 513401,
        "frameNumLen": 0,
        "id": 358,
        "motorNumLen": 6,
        "name": "西昌",
        "prefix": "川W",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "xilinguole",
        "cityCode": 1525,
        "frameNumLen": 6,
        "id": 39,
        "motorNumLen": 6,
        "name": "锡林郭勒盟",
        "prefix": "蒙H",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "xingan",
        "cityCode": 1522,
        "frameNumLen": 6,
        "id": 38,
        "motorNumLen": 6,
        "name": "兴安盟",
        "prefix": "蒙F",
        "province": "内蒙古",
        "valid": true
      },
      {
        "PY": "xingtai",
        "cityCode": 1305,
        "frameNumLen": 4,
        "id": 9,
        "motorNumLen": 0,
        "name": "邢台",
        "prefix": "冀E",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "xining",
        "cityCode": 6301,
        "frameNumLen": -1,
        "id": 323,
        "motorNumLen": 6,
        "name": "西宁",
        "prefix": "青A",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "xinxiang",
        "cityCode": 4107,
        "frameNumLen": -1,
        "id": 166,
        "motorNumLen": 6,
        "name": "新乡",
        "prefix": "豫G",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "xinyang",
        "cityCode": 4115,
        "frameNumLen": 0,
        "id": 174,
        "motorNumLen": 6,
        "name": "信阳",
        "prefix": "豫S",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "xinyu",
        "cityCode": 3605,
        "frameNumLen": 6,
        "id": 133,
        "motorNumLen": 6,
        "name": "新余",
        "prefix": "赣K",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "xinzhou",
        "cityCode": 1409,
        "frameNumLen": 6,
        "id": 25,
        "motorNumLen": 0,
        "name": "忻州",
        "prefix": "晋H",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "xishuangbanna",
        "cityCode": 5328,
        "frameNumLen": -1,
        "id": 286,
        "motorNumLen": 0,
        "name": "西双版纳傣族自治州",
        "prefix": "云K",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "xuancheng",
        "cityCode": 3418,
        "frameNumLen": 6,
        "id": 118,
        "motorNumLen": 6,
        "name": "宣城",
        "prefix": "皖P",
        "province": "安徽",
        "valid": true
      },
      {
        "PY": "xuchang",
        "cityCode": 4110,
        "frameNumLen": 0,
        "id": 169,
        "motorNumLen": 6,
        "name": "许昌",
        "prefix": "豫K",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "xuzhou",
        "cityCode": 3203,
        "frameNumLen": 0,
        "id": 81,
        "motorNumLen": 6,
        "name": "徐州",
        "prefix": "苏C",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "yaan",
        "cityCode": 5118,
        "frameNumLen": 6,
        "id": 260,
        "motorNumLen": 6,
        "name": "雅安",
        "prefix": "川T",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "yanan",
        "cityCode": 6106,
        "frameNumLen": -1,
        "id": 303,
        "motorNumLen": 6,
        "name": "延安",
        "prefix": "陕J",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "yanbei",
        "cityCode": 1423,
        "frameNumLen": 6,
        "id": 28,
        "motorNumLen": 0,
        "name": "雁北",
        "prefix": "晋G",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "yanbian",
        "cityCode": 2224,
        "frameNumLen": 4,
        "id": 63,
        "motorNumLen": 6,
        "name": "延边朝鲜族自治州",
        "prefix": "吉H",
        "province": "吉林",
        "valid": true
      },
      {
        "PY": "yancheng",
        "cityCode": 3209,
        "frameNumLen": 0,
        "id": 87,
        "motorNumLen": 4,
        "name": "盐城",
        "prefix": "苏J",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "yangjiang",
        "cityCode": 4417,
        "frameNumLen": 6,
        "id": 218,
        "motorNumLen": 6,
        "name": "阳江",
        "prefix": "粤Q",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "yanglinggaoxinnongyeshifanqu",
        "cityCode": 6125,
        "frameNumLen": -1,
        "id": 308,
        "motorNumLen": 6,
        "name": "杨凌高新农业示范区",
        "prefix": "陕V",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "yangpukaifaqu",
        "cityCode": 4606,
        "frameNumLen": -1,
        "id": 244,
        "motorNumLen": 0,
        "name": "洋浦开发区",
        "prefix": "琼E",
        "province": "海南",
        "valid": true
      },
      {
        "PY": "yangquan",
        "cityCode": 1403,
        "frameNumLen": 6,
        "id": 19,
        "motorNumLen": 0,
        "name": "阳泉",
        "prefix": "晋C",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "yangzhou",
        "cityCode": 3210,
        "frameNumLen": 6,
        "id": 88,
        "motorNumLen": 0,
        "name": "扬州",
        "prefix": "苏K",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "yantai",
        "cityCode": 3706,
        "frameNumLen": -1,
        "id": 146,
        "motorNumLen": 0,
        "name": "烟台",
        "prefix": "鲁F",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "yibin",
        "cityCode": 5115,
        "frameNumLen": 6,
        "id": 257,
        "motorNumLen": 6,
        "name": "宜宾",
        "prefix": "川Q",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "yichang",
        "cityCode": 4205,
        "frameNumLen": 5,
        "id": 180,
        "motorNumLen": 0,
        "name": "宜昌",
        "prefix": "鄂E",
        "province": "湖北",
        "valid": true
      },
      {
        "PY": "yichun",
        "cityCode": 3609,
        "frameNumLen": 6,
        "id": 137,
        "motorNumLen": 6,
        "name": "宜春",
        "prefix": "赣C",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "yichun_h",
        "cityCode": 2307,
        "frameNumLen": -1,
        "id": 70,
        "motorNumLen": 0,
        "name": "伊春",
        "prefix": "黑F",
        "province": "黑龙江",
        "valid": true
      },
      {
        "PY": "yili",
        "cityCode": 6540,
        "frameNumLen": 6,
        "id": 347,
        "motorNumLen": 0,
        "name": "伊犁哈萨克自治州",
        "prefix": "新F",
        "province": "新疆",
        "valid": true
      },
      {
        "PY": "yinchuan",
        "cityCode": 6401,
        "frameNumLen": 0,
        "id": 331,
        "motorNumLen": 6,
        "name": "银川",
        "prefix": "宁A",
        "province": "宁夏",
        "valid": true
      },
      {
        "PY": "yingkou",
        "cityCode": 2108,
        "frameNumLen": -1,
        "id": 48,
        "motorNumLen": 6,
        "name": "营口",
        "prefix": "辽H",
        "province": "辽宁",
        "valid": true
      },
      {
        "PY": "yingtan",
        "cityCode": 3606,
        "frameNumLen": 6,
        "id": 134,
        "motorNumLen": 6,
        "name": "鹰潭",
        "prefix": "赣L",
        "province": "江西",
        "valid": true
      },
      {
        "PY": "yiyang",
        "cityCode": 4309,
        "frameNumLen": 4,
        "id": 198,
        "motorNumLen": 6,
        "name": "益阳",
        "prefix": "湘H",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "yongzhou",
        "cityCode": 4311,
        "frameNumLen": 0,
        "id": 200,
        "motorNumLen": 6,
        "name": "永州",
        "prefix": "湘M",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "yueyang",
        "cityCode": 4306,
        "frameNumLen": 0,
        "id": 195,
        "motorNumLen": 6,
        "name": "岳阳",
        "prefix": "湘F",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "yulin",
        "cityCode": 4509,
        "frameNumLen": 0,
        "id": 235,
        "motorNumLen": 6,
        "name": "玉林",
        "prefix": "桂K",
        "province": "广西",
        "valid": true
      },
      {
        "PY": "yulin",
        "cityCode": 6108,
        "frameNumLen": -1,
        "id": 305,
        "motorNumLen": 6,
        "name": "榆林",
        "prefix": "陕K",
        "province": "陕西",
        "valid": true
      },
      {
        "PY": "yuncheng",
        "cityCode": 1408,
        "frameNumLen": 6,
        "id": 24,
        "motorNumLen": 0,
        "name": "运城",
        "prefix": "晋M",
        "province": "山西",
        "valid": true
      },
      {
        "PY": "yunfu",
        "cityCode": 4453,
        "frameNumLen": 6,
        "id": 224,
        "motorNumLen": 6,
        "name": "云浮",
        "prefix": "粤W",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "yushucangzuzizhizhou",
        "cityCode": 6327,
        "frameNumLen": -1,
        "id": 329,
        "motorNumLen": 6,
        "name": "玉树藏族自治州",
        "prefix": "青G",
        "province": "青海",
        "valid": true
      },
      {
        "PY": "yuxi",
        "cityCode": 5304,
        "frameNumLen": -1,
        "id": 277,
        "motorNumLen": 0,
        "name": "玉溪",
        "prefix": "云F",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "zaozhuang",
        "cityCode": 3704,
        "frameNumLen": -1,
        "id": 144,
        "motorNumLen": 6,
        "name": "枣庄",
        "prefix": "鲁D",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "zhangjiagang",
        "cityCode": 1307,
        "frameNumLen": 7,
        "id": 11,
        "motorNumLen": 5,
        "name": "张家口",
        "prefix": "冀G",
        "province": "河北",
        "valid": true
      },
      {
        "PY": "zhangjiajie",
        "cityCode": 4308,
        "frameNumLen": 0,
        "id": 197,
        "motorNumLen": 6,
        "name": "张家界",
        "prefix": "湘G",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "zhangye",
        "cityCode": 6207,
        "frameNumLen": -1,
        "id": 315,
        "motorNumLen": 0,
        "name": "张掖",
        "prefix": "甘G",
        "province": "甘肃",
        "valid": true
      },
      {
        "PY": "zhangzhou",
        "cityCode": 3506,
        "frameNumLen": 4,
        "id": 124,
        "motorNumLen": 0,
        "name": "漳州",
        "prefix": "闽E",
        "province": "福建",
        "valid": true
      },
      {
        "PY": "zhanjiang",
        "cityCode": 4408,
        "frameNumLen": 6,
        "id": 211,
        "motorNumLen": 6,
        "name": "湛江",
        "prefix": "粤G",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "zhaoqing",
        "cityCode": 4412,
        "frameNumLen": 6,
        "id": 213,
        "motorNumLen": 6,
        "name": "肇庆",
        "prefix": "粤H",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "zhaotong",
        "cityCode": 5306,
        "frameNumLen": -1,
        "id": 279,
        "motorNumLen": 0,
        "name": "昭通",
        "prefix": "云C",
        "province": "云南",
        "valid": true
      },
      {
        "PY": "zhengzhou",
        "cityCode": 4101,
        "frameNumLen": -1,
        "id": 160,
        "motorNumLen": 0,
        "name": "郑州",
        "prefix": "豫A",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "zhenjiang",
        "cityCode": 3211,
        "frameNumLen": 4,
        "id": 89,
        "motorNumLen": 6,
        "name": "镇江",
        "prefix": "苏L",
        "province": "江苏",
        "valid": true
      },
      {
        "PY": "zhongshan",
        "cityCode": 4420,
        "frameNumLen": 6,
        "id": 221,
        "motorNumLen": 6,
        "name": "中山",
        "prefix": "粤T",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "zhongwei",
        "cityCode": 6405,
        "frameNumLen": 0,
        "id": 335,
        "motorNumLen": 6,
        "name": "中卫",
        "prefix": "宁E",
        "province": "宁夏",
        "valid": true
      },
      {
        "PY": "zhoukou",
        "cityCode": 4116,
        "frameNumLen": -1,
        "id": 175,
        "motorNumLen": 6,
        "name": "周口",
        "prefix": "豫P",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "zhoushan",
        "cityCode": 3309,
        "frameNumLen": 6,
        "id": 100,
        "motorNumLen": 0,
        "name": "舟山",
        "prefix": "浙L",
        "province": "浙江",
        "valid": true
      },
      {
        "PY": "zhuhai",
        "cityCode": 4404,
        "frameNumLen": 6,
        "id": 207,
        "motorNumLen": 6,
        "name": "珠海",
        "prefix": "粤C",
        "province": "广东",
        "valid": true
      },
      {
        "PY": "zhumadian",
        "cityCode": 4117,
        "frameNumLen": 5,
        "id": 176,
        "motorNumLen": 6,
        "name": "驻马店",
        "prefix": "豫Q",
        "province": "河南",
        "valid": true
      },
      {
        "PY": "zhuzhou",
        "cityCode": 4302,
        "frameNumLen": 0,
        "id": 191,
        "motorNumLen": 6,
        "name": "株洲",
        "prefix": "湘B",
        "province": "湖南",
        "valid": true
      },
      {
        "PY": "zibo",
        "cityCode": 3703,
        "frameNumLen": -1,
        "id": 143,
        "motorNumLen": 0,
        "name": "淄博",
        "prefix": "鲁C",
        "province": "山东",
        "valid": true
      },
      {
        "PY": "zigong",
        "cityCode": 5103,
        "frameNumLen": 6,
        "id": 246,
        "motorNumLen": 6,
        "name": "自贡",
        "prefix": "川C",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "ziyang",
        "cityCode": 5120,
        "frameNumLen": 6,
        "id": 262,
        "motorNumLen": 6,
        "name": "资阳",
        "prefix": "川M",
        "province": "四川",
        "valid": true
      },
      {
        "PY": "zunyi",
        "cityCode": 5203,
        "frameNumLen": 0,
        "id": 268,
        "motorNumLen": 6,
        "name": "遵义",
        "prefix": "贵C",
        "province": "贵州",
        "valid": true
      }
    ];
});